### ISSUE TITLE
FATAL EXCEPTION: com.mixpanel.android.AnalyticsWorker

### ISSUE THREAD

**Issue by romatallinn** [mixpanel/mixpanel-flutter#114]
Cannot say much about the issue, but to attach the logs. Maybe flutter 3.10 problem?

<details><summary>Doctor</summary>
<p>

```

[✓] Flutter (Channel stable, 3.10.2, on macOS 13.3.1 22E772610a darwin-x64, locale en-NO)
    • Flutter version 3.10.2 on channel stable at /Users/rsirokov/Projects/Plugins/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (4 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/rsirokov/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/rsirokov/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/rsirokov/Library/Android/sdk
    • Java binary at: /Users/rsirokov/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/rsirokov/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (3 available)
    *****
```
</p>
</details> 

<details><summary>Error</summary>
<p>

```

E/AndroidRuntime(17856): FATAL EXCEPTION: com.mixpanel.android.AnalyticsWorker
E/AndroidRuntime(17856): Process: com.dizconto.app.android, PID: 17856
E/AndroidRuntime(17856): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/perf/network/FirebasePerfUrlConnection;
E/AndroidRuntime(17856): 	at com.mixpanel.android.util.HttpService.performRequest(HttpService.java:110)
E/AndroidRuntime(17856): 	at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendData(AnalyticsMessages.java:516)
E/AndroidRuntime(17856): 	at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendAllData(AnalyticsMessages.java:488)
E/AndroidRuntime(17856): 	at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:420)
E/AndroidRuntime(17856): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(17856): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(17856): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/AndroidRuntime(17856): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.perf.network.FirebasePerfUrlConnection" on path: DexPathList[[zip file "/data/app/~~wY9zF0IBav_p91mGcPdRaw==/com.dizconto.app.android-Tol6RXvfK7txoZFtjx3fNw==/base.apk"],nativeLibraryDirectories=[/data/app/~~wY9zF0IBav_p91mGcPdRaw==/com.dizconto.app.android-Tol6RXvfK7txoZFtjx3fNw==/lib/arm, /data/app/~~wY9zF0IBav_p91mGcPdRaw==/com.dizconto.app.android-Tol6RXvfK7txoZFtjx3fNw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/system_ext/lib]]
E/AndroidRuntime(17856): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(17856): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(17856): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(17856): 	... 7 more
I/Process (17856): Sending signal. PID: 17856 SIG: 9
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"94","method":"getMemoryUsage","params":{"isolateId":"isolates/3523976964750335"}}

```

</p>
</details>

**Comment by romatallinn** [comment]
Yikes, turns out that when cleaning unused Firebase dependencies (in particular, the Performance module), I didn't remove some dependencies in the gradle file. And was confused by the logs when it threw an exception as in Mixpanel.
