### ISSUE TITLE
App crash on init

### ISSUE THREAD

**Issue by itsJoKr** [mixpanel/mixpanel-flutter#32]
Added Mixpanel to the project. All looked fine for first the first week, but randomly it got into some state and keeps crashing every time I start the app.

I cannot give you any smart info. I'm not sure why it started happening. I am wondering why is jacocoInit called in the production, as Jacoco is test coverage tool and should never be shipped with SDK or called for any functionality of SDK.

We don't want to ship app with Mixpanel if this can happen in prod.

```
 java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_8ff85ea/Offline;
E/AndroidRuntime( 8706): 	at com.mixpanel.android.mpmetrics.MixpanelAPI.$jacocoInit(Unknown Source:13)
E/AndroidRuntime( 8706): 	at com.mixpanel.android.mpmetrics.MixpanelAPI.<clinit>(Unknown Source:0)
E/AndroidRuntime( 8706): 	at com.mixpanel.android.mpmetrics.MixpanelAPI.getInstance(Unknown Source:0)
E/AndroidRuntime( 8706): 	at com.mixpanel.mixpanel_flutter.MixpanelFlutterPlugin.handleInitialize(MixpanelFlutterPlugin.java:200)
E/AndroidRuntime( 8706): 	at com.mixpanel.mixpanel_flutter.MixpanelFlutterPlugin.onMethodCall(MixpanelFlutterPlugin.java:57)
E/AndroidRuntime( 8706): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime( 8706): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime( 8706): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime( 8706): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 8706): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime( 8706): 	at android.os.Looper.loop(Looper.java:183)
E/AndroidRuntime( 8706): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 8706): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8706): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 8706): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 8706): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_8ff85ea.Offline" on path: DexPathList[[zip file "/data/app/~~dq_vkkkHt5VvFPJsBwHICg==/com.infinum.modra.dev-GIYqXYbCIicC5pCeyCS8LA==/base.apk"],nativeLibraryDirectories=[/data/app/~~dq_vkkkHt5VvFPJsBwHICg==/com.infinum.modra.dev-GIYqXYbCIicC5pCeyCS8LA==/lib/x86, /data/app/~~dq_vkkkHt5VvFPJsBwHICg==/com.infinum.modra.dev-GIYqXYbCIicC5pCeyCS8LA==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime( 8706): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime( 8706): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 8706): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by ganeshrvel** [comment]
To fix `non-null` version of the `mixpanel-flutter` people can use this pubspec value

```
  # Mixpanel
  mixpanel_flutter: #^1.0.1
    git:
      url: https://github.com/frontrow-tech/mixpanel-flutter
      ref: afc00bc6e66e46782953a6d42099b8f97d5ace3f
```

**Comment by zihejia** [comment]
The issue has been fixed(v5.9.4) on the android side, so it should be good to go for now, just re-sync everything and make sure to clean the cache. Sorry about the inconvenience! I'm closing this one now, please feel free to reopen if the problem still exists.
