### ISSUE TITLE
Failed resolution of FirebasePerfUrlConnection

### ISSUE THREAD

**Issue by phildupuis** [mixpanel/mixpanel-flutter#34]
We added mixpanel to our project and everything worked well on iOS, but on Android, this integration gave us systematic crash on boot
```
FATAL EXCEPTION: com.mixpanel.android.AnalyticsWorker
    Process: health.braver.pro, PID: 12549
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/perf/network/FirebasePerfUrlConnection;
        at d.g.a.b.b.b(HttpService.java:3)
        at d.g.a.a.d.b(DecideChecker.java:4)
        at d.g.a.a.d.d(DecideChecker.java:19)
        at d.g.a.a.d.f(DecideChecker.java:1)
        at d.g.a.a.d.g(DecideChecker.java:3)
        at d.g.a.a.a$i$a.handleMessage(AnalyticsMessages.java:56)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

This might be related to https://github.com/mixpanel/mixpanel-flutter/issues/32 and https://github.com/mixpanel/mixpanel-flutter/issues/33, but we did not found any solution that worked for us. 

We ended up adding `implementation 'com.google.firebase:firebase-perf:20.0.3'` to our build.gradle and this fixed the crash.

Could there be something wrong with our setup ?

**Comment by zihejia** [comment]
hi @phildupuis , thanks for bringing it up. Please try our latest version 1.4.2 which has a fix for this exception. I'm closing this one now, please feel free to reopen if the problem still exists.
